apiVersion: v1
kind: Service
metadata:
  name: omni-db-svc
spec:
  type: NodePort
  selector:
    proyecto: omni-db
    tipo: db
  ports:
    - protocol: TCP
      nodePort: 3000x
      port: 3000x
      targetPort: 8080
