apiVersion: v1
kind: Service
metadata:
  name: {nombre-proyecto}
spec:
  type: NodePort
  selector:
    proyecto: {nombre-proyecto}
    tipo: {tag-tipo-proyecto}
  ports:
    - protocol: TCP
      nodePort: 3000x
      port: 3000x
      targetPort: 80
