apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
data:
  config.toml: |-
    concurrent = 4
    [session_server]
      listen_address = "[::]:8252"
      session_timeout = 600
      [[runners]]
        name = "gitlab-runner-gitlab-XXXXXXX"
        url = "https://gitaddress/"
        token = "token" 
        executor = "kubernetes"
        [runners.cache]
        [runners.kubernetes]
        namespace = "gitlab-runner"
        privileged = true
        poll_timeout = 600
        cpu_request = "1"
        service_cpu_request = "200m"
        disable_cache = false
        tls_verify = false
        [[runners.kubernetes.volumes.host_path]]
            name = "docker"
            mount_path = "/var/run/docker.sock"
            host_path = "/var/run/docker.sock"
